name: main

on: 
  push:
  pull_request:
  schedule:
    - cron: "15 2 23 * *" #run job on the 23rd day of every month on the 15th minute of the 2nd hour

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        smalltalk: [ 3.7.0 ]
    runs-on: ${{ matrix.os }}
    env:
      GS_VERS: ${{ matrix.smalltalk }}
      PLATFORM: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - id: test_GsDevKit_stones
        uses: dalehenrich/setup-superDoit@v4
        with:
          gemstone-version: ${{ matrix.smalltalk }}
          superDoit-branch: 'v4.1'        
      - name: initial setup
        run: |
          export STONES_HOME="$(pwd)"
          export GEMSTONE_ROOT=${{ steps.setup-superDoit.outputs.gemstone-product-path }}
          export SUPERDOIT_ROOT=${{ steps.setup-superDoit.outputs.superDoit-root }}
          export WORK_ROOT="$GITHUB_WORKSPACE/.."
          echo "STONES_HOME=$STONES_HOME"
          echo "GEMSTONE_ROOT=$GEMSTONE_ROOT"
          echo "SUPERDOIT_ROOT=$SUPERDOIT_ROOT"
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          echo "$GEMSTONE_NAME"
          echo "WORK_ROOT"
          ls -altr $WORK_ROOT
          echo "$GITHUB_WORKSPACE"
          ls -altr $GITHUB_WORKSPACE
        shell: bash
  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - build
    runs-on: ubuntu-20.04
    steps:
       - name: Slack Workflow Notification
         uses: Gamesight/slack-workflow-status@master
         with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_DALEHENRICH}}
          name: 'action run' 
